
apiVersion: v1
kind: ConfigMap
metadata:
  name: trading-api-gateway-config-map
  namespace: trading-dev

data:
  CORS_ALLOWED_ORIGIN: http://localhost:4200
  EXCHANGE_SERVICE_URL: http://exchange:8080
  TRADE_ENRICHER_SERVICE_URL: http://trade-enricher:8080
  TRADE_PROCESSOR_SERVICE: http://trade-processor:8080
  REF_DATA_PROVIDER_SERVICE: http://refdata-provider:8080
  SERVER_PORT: 8080