package com.learn.ssl.enable.analytics.dto;

import lombok.Data;

/**
 * DTO representing analytics event data
 * consumed from Kafka topics.
 *
 * <p>
 * This event is generated by upstream services
 * such as Flight Search Service whenever
 * users perform flight-related actions.
 * </p>
 */
@Data
public class AnalyticsEvent {

    /**
     * Type of analytics event.
     * Example:
     * FLIGHT_SEARCHED
     */
    private String eventType;

    /**
     * Source / departure location.
     * Example:  Bangalore
     */
    private String from;

    /**
     * Destination / arrival location.
     * Example:  Delhi
     */
    private String to;

    /**
     * Journey travel date.
     * Example: 2026-05-10
     */
    private String travelDate;

    /**
     * Total number of travelers.
     */
    private Integer travelerCount;

    /**
     * Event creation timestamp.
     * Example:
     * 2026-05-10T10:15:30
     */
    private String timestamp;

}