
apiVersion: v1
kind: Service
metadata:
  name: trading-api-gateway
  namespace: trading-dev
  labels:
    app: trading-api-gateway
    version: v1

spec:
  type: LoadBalancer
  selector:
    app: trading-api-gateway
    version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080