
apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-enricher-config-map
  namespace: trading-dev
  
data:
  SERVER_PORT: "9062"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
  CONSUMER_TRADE_ENRICHER_TOPIC: nse.trade.events
  PRODUCER_TRADE_ENRICHER_TOPIC: nse.enriched.trade.events