
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-api-gateway-deployment-aws
  namespace: trading-dev-aws
  labels:
    app: trading-api-gateway-deployment-aws
    version: v1

spec:
  replicas: 1

  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: trading-api-gateway-aws
      version: v1

  template:
    metadata:
      labels:
        app: trading-api-gateway-aws
        version: v1

      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: trading-api-gateway-container
          image: trading-api-gateway:v1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: SERVICE_NAME
              value: trading-api-gateway

          envFrom:
            - configMapRef:
                name: trading-api-gateway-config-map-aws


          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits: 
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          startupProbe:
            httpGet:
              path: "/actuator/health"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

      


