
apiVersion: v1
kind: Service
metadata:
  name: trading-api-gateway-service-aws
  namespace: trading-dev-aws
  labels:
    app: trading-api-gateway-aws
    version: v1

spec:
  type: ClusterIP
  selector:
    app: trading-api-gateway-aws
    version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 8080