
apiVersion: v1
kind: Service
metadata:
  name: refdata-provider
  namespace: trading-dev
  labels:
    app: refdata-provider
    version: v1
    
spec:
  type: ClusterIP
  selector: 
    app: refdata-provider
    version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 9063