spring.application.name=exchange

server.port=9061


# Kafka Producer Bootstrap
spring.kafka.bootstrap-servers=localhost:9092

# Performance / Batching
kafka.producer.batch-size=16384
kafka.producer.linger-ms=5
kafka.producer.compression-type=lz4

# Reliability
kafka.producer.ack-strategy=all
kafka.producer.retries=5
kafka.producer.retry-backoff-ms=1000
kafka.producer.idempotence=true

# Timeouts
kafka.producer.request-timeout=30000
kafka.producer.delivery-timeout=120000

# Serializers
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Transaction
kafka.producer.trans-id-prefix=exchange-producer

#Topic
exchange.msg.producer.topic=nse.trade.events

#spring.kafka.properties.security.protocol=SASL_SSL
#spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM

#spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;

#spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler