apiVersion: v1
kind: ServiceAccount
metadata:
  name: exchange-service-sa
  namespace: trading-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::336042380202:role/JavaLearnerExchangeServiceMSKProducerRole