
apiVersion: v1
kind: ConfigMap
metadata:
  name: refdata-provider-config-map-aws
  namespace: trading-dev-aws
  
data:
  KAFKA_PRODUCER_BOOTSTRAP_SERVERS: localhost:9092
  SERVER_PORT: 9061
  EXCHANGE_MSG_PRODUCER_TOPIC: nse.trade.events