
apiVersion: v1
kind: Service
metadata:
  name: trade-enricher
  namespace: trading-dev
  labels:
    app: trade-enricher
    version: v1
    
spec:
  type: ClusterIP
  selector: 
    app: trade-enricher
    version: v1
  ports:
    - name: http
      port: 8080
      targetPort: 9062